### ISSUE TITLE
The reference of this code

### ISSUE THREAD

**Issue by Sytronik** [idnavid/py_vad_tool#3]
Hi, I'm using your code usefully thanks to its simplicity.

I wonder what you referred to when you write this code.
I'd like to modify this code for my environment,
but It's hard for me because I don't get what the existing code exactly means.
I hope you can recommend me a paper, a book, or anything else.

Thanks.

**Comment by idnavid** [comment]
Hi, 
I'm happy that you've found the code useful. 

The knowledge used in developing the code is mostly based on several years of experience with speech systems and what was commonly used in our Center (CRSS in UTD). Not that there's no reference, rather the knowledge is fairly common and that I can't think of any specific reference. 

I'm happy to help out with any specific questions or add comments/docstrings to help you out.  The overall idea is to calculate the energy of each frame and threshold it. 

Thanks, 
Navid

**Comment by dathu** [comment]
Hi idnavid,

  Thankyou very much the code was very simple and useful for me.
